//
//  NetworkingJapxViewController.swift
//  Catalog
//
//  Created by Mate Masnov on 02/12/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NetworkingJapxViewController: UIViewController {

    // MARK: - Public properties -

    @IBOutlet weak var passwordTextField: UITextField!
    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var usernameTextField: UITextField!
    
    @IBOutlet weak var createUserButton: UIButton!
    @IBOutlet weak var getUserButton: UIButton!
    @IBOutlet weak var updateUserButton: UIButton!
    @IBOutlet weak var deleteUserButton: UIButton!
    
    var presenter: NetworkingJapxPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        shouldEnableCreateUserButtonAndDisableOthers(true)
    }
	
    @IBAction func createUserActionHandler(_ sender: Any) {
        
        self.createUserButton.isEnabled = !self.createUserButton.isEnabled
        presenter.didPressCreate(with: emailTextField.text, username: usernameTextField.text, password: passwordTextField.text)
    }
    
    @IBAction func getUserActionHandler(_ sender: Any) {
        presenter.didPressGet()
    }
    
    @IBAction func updateUserActionHandler(_ sender: Any) {
        presenter.didPressUpdate(email: emailTextField.text, username: usernameTextField.text)
    }
    
    @IBAction func deleteUserActionHandler(_ sender: Any) {
        presenter.didPressDelete()
    }
}

// MARK: - Extensions -

extension NetworkingJapxViewController: NetworkingJapxViewInterface {
    
    func shouldEnableCreateUserButtonAndDisableOthers(_ shouldEnable: Bool) {
        self.createUserButton.isEnabled = shouldEnable
        self.getUserButton.isEnabled = !shouldEnable
        self.updateUserButton.isEnabled = !shouldEnable
        self.deleteUserButton.isEnabled = !shouldEnable
        
        self.createUserButton.alpha = shouldEnable ? 1 : 0.3
        
        let alphaForOther: CGFloat = shouldEnable ? 0.3 : 1
        
        self.getUserButton.alpha = alphaForOther
        self.updateUserButton.alpha = alphaForOther
        self.deleteUserButton.alpha = alphaForOther
    }
    
}

extension NetworkingJapxViewController: Catalogizable {
    
    static var title: String {
        return "Japx Networking"
    }
    
    static var viewController: UIViewController {
        return NetworkingJapxWireframe().viewController
    }
    
}
