//
//  NetworkingJapxWireframe.swift
//  Catalog
//
//  Created by Mate Masnov on 02/12/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

final class NetworkingJapxWireframe: BaseWireframe {

    // MARK: - Private properties -
    
    private let _storyboard = UIStoryboard(name: "NetworkingJapx", bundle: nil)
    
    // MARK: - Module setup -
    
    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: NetworkingJapxViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = NetworkingJapxInteractor(sessionManager: SessionManager.default)
        let presenter = NetworkingJapxPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension NetworkingJapxWireframe: NetworkingJapxWireframeInterface {
    
    func displayInfoAlert(with title: String?, message: String?) {
        displayInfoAlert(with: title, message: message, completion: nil)
    }
    
    func displayInfoAlert(with title: String?, message: String?, completion: ((UIAlertAction) -> Void)?) {
        displayAlert(
            with: title,
            message: message,
            actions: [UIAlertAction(title: "OK", style: .cancel, handler: completion)],
            style: .alert
        )
    }
    
    func displayAlert(with title: String?, message: String?, actions: [UIAlertAction], style: UIAlertController.Style) {
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        actions.forEach { alertController.addAction($0) }
        
        navigationController?.present(alertController, animated: true, completion: nil)
    }
}
