//
//  NetworkingJapxWireframe.swift
//  Catalog
//
//  Created by Mate Masnov on 02/12/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

final class NetworkingJapxWireframe: BaseWireframe {

    // MARK: - Private properties -
    
    private let _storyboard = UIStoryboard(name: "NetworkingJapx", bundle: nil)
    
    // MARK: - Module setup -
    
    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: NetworkingJapxViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = NetworkingJapxInteractor(sessionManager: SessionManager.default)
        let presenter = NetworkingJapxPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension NetworkingJapxWireframe: NetworkingJapxWireframeInterface {

    func navigate(to option: NetworkingJapxNavigationOption) {
    }
}
