//
//  NetworkingJapxInterfaces.swift
//  Catalog
//
//  Created by Mate Masnov on 02/12/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

enum NetworkingJapxNavigationOption {
}

protocol NetworkingJapxWireframeInterface: WireframeInterface, Progressable {
    func navigate(to option: NetworkingJapxNavigationOption)
}

protocol NetworkingJapxViewInterface: ViewInterface, Progressable {
    func shouldEnableCreateUserButtonAndDisableOthers(_ shouldEnable: Bool)
}

protocol NetworkingJapxPresenterInterface: PresenterInterface {
    func didPressCreate(with email: String?, username: String?, password: String?)
    func didPressUpdate(email: String?, username: String?)
    func didPressGet()
    func didPressDelete()
}

protocol NetworkingJapxInteractorInterface: InteractorInterface {
    func createUser(email: String, username: String, password: String, passwordConfirmation: String, completion: @escaping (Result<PokedexUser>) -> Void) -> DataRequest
    func getUser(id: String, completion: @escaping (Result<PokedexUser>) -> Void) -> DataRequest
    func updateUser(id: String, email: String?, username: String?, completion: @escaping (Result<PokedexUser>) -> Void) -> DataRequest
    func deleteUser(id: String, completion: @escaping (Result<Void>) -> Void) -> DataRequest
    func setAdapter(_ adapter: PokedexTokenAdapter)
}
