//
//  NetworkingInterfaces.swift
//  Catalog
//
//  Created by Filip Gulan on 25/04/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol NetworkingWireframeInterface: WireframeInterface {
}

protocol NetworkingViewInterface: ViewInterface {
}

protocol NetworkingPresenterInterface: PresenterInterface {
}

protocol NetworkingInteractorInterface: InteractorInterface {
}
