//
//  NetworkingInteractor.swift
//  Catalog
//
//  Created by Filip Gulan on 25/04/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class NetworkingInteractor {
}

// MARK: - Extensions -

extension NetworkingInteractor: NetworkingInteractorInterface {
}
