//
//  NetworkingWireframe.swift
//
//  Created by Filip Gulan on 25/04/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NetworkingWireframe: BaseWireframe {

    // MARK: - Module setup -

    init() {
        let moduleViewController = NetworkingViewController()
        super.init(viewController: moduleViewController)
        
        let interactor = NetworkingInteractor()
        let presenter = NetworkingPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension NetworkingWireframe: NetworkingWireframeInterface {
}
