# Parent config - Infinum Style Guide
 parent_config: https://raw.githubusercontent.com/infinum/swift-style-guide/master/.swiftlint.yml

included:
  - .
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Tests
