//
//  RxNetworkingWireframe.swift
//
//  Created by Filip Gulan on 25/04/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class RxNetworkingWireframe: BaseWireframe {

    // MARK: - Module setup -

    init() {
        let moduleViewController = RxNetworkingViewController()
        super.init(viewController: moduleViewController)
        
        let interactor = RxNetworkingInteractor()
        let presenter = RxNetworkingPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension RxNetworkingWireframe: RxNetworkingWireframeInterface {
}
