//
//  CombineNetworkingInterfaces.swift
//  Catalog
//
//  Created by Zvonimir Medak on 29.10.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import Alamofire

protocol CombineNetworkingWireframeInterface: WireframeInterface {
}

protocol CombineNetworkingViewInterface: ViewInterface {
}

@available(iOS 13, *)
protocol CombineNetworkingPresenterInterface: PresenterInterface {
    func configure(with output: CombineNetworking.ViewOutput) -> CombineNetworking.ViewInput
}

@available(iOS 13, *)
protocol CombineNetworkingInteractorInterface: InteractorInterface {
    func login(_ email: String, _ password: String) -> AnyPublisher<Void, AFError>
}

@available(iOS 13, *)
enum CombineNetworking {

    struct ViewOutput {
        let email: AnyPublisher<String, Never>
        let password: AnyPublisher<String, Never>
        let login: AnyPublisher<Void, Never>
    }

    struct ViewInput {
        let didLogin: AnyPublisher<Bool, AFError>
    }
}
