//
//  CombineNetworkingInteractor.swift
//  Catalog
//
//  Created by Zvonimir Medak on 29.10.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine
import Alamofire

final class CombineNetworkingInteractor {

    private let service: APIService
    private let sessionManager: SessionManager

    init(service: APIService = .instance, sessionManager: SessionManager = .default) {
        self.service = service
        self.sessionManager = sessionManager
    }
}

// MARK: - Extensions -
@available(iOS 13, *)
extension CombineNetworkingInteractor: CombineNetworkingInteractorInterface {
    func login(_ email: String, _ password: String) -> AnyPublisher<Void, AFError> {
        return service
            .requestCompletablePublisher(
                router: LoginRouter.login(email: email, password: password),
                session: sessionManager.session
            )
    }

}
