//
//  CombineHapticFeedbackViewController.swift
//  Catalog
//
//  Created by Zvonimir Medak on 15.09.2022..
//  Copyright (c) 2022 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import CombineCocoa
import CombineExt

@available(iOS 13, *)
final class CombineHapticFeedbackViewController: UIViewController {

    // MARK: - IBOutlets -

    @IBOutlet private weak var selectionFeedbackButton: UIButton!
    @IBOutlet private weak var successFeedbackButton: UIButton!
    @IBOutlet private weak var failureFeedbackButton: UIButton!
    @IBOutlet private weak var impactFeedbackButton: UIButton!
    
    // MARK: - Private properties -

    private var cancellables: Set<AnyCancellable> = []

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

@available(iOS 13, *)
private extension CombineHapticFeedbackViewController {

    func setupView() {
        selectionFeedbackButton
            .tapPublisher
            .selectionHapticFeedback()
            .sink(receiveValue: { })
            .store(in: &cancellables)

        successFeedbackButton
            .tapPublisher
            .successHapticFeedback()
            .sink(receiveValue: { })
            .store(in: &cancellables)

        failureFeedbackButton
            .tapPublisher
            .failureHapticFeedback()
            .sink(receiveValue: { })
            .store(in: &cancellables)

        impactFeedbackButton
            .tapPublisher
            .impactHapticFeedback()
            .sink(receiveValue: { })
            .store(in: &cancellables)
    }
}

@available(iOS 13, *)
extension CombineHapticFeedbackViewController: Catalogizable {

    static var title: String {
        return "Combine Haptic Feedback Controller"
    }

    static var viewController: UIViewController {
        return UIStoryboard(name: "CombineHapticFeedback", bundle: nil)
            .instantiateViewController(ofType: CombineHapticFeedbackViewController.self)
    }
}
