//
//  CombinePagingInterfaces.swift
//  Catalog
//
//  Created by Zvonimir Medak on 02.11.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine
import Alamofire

protocol CombinePagingWireframeInterface: WireframeInterface {
}

protocol CombinePagingViewInterface: ViewInterface {
}

@available(iOS 13, *)
protocol CombinePagingPresenterInterface: PresenterInterface {
    func configure(with output: CombinePagingExample.ViewOutput) -> CombinePagingExample.ViewInput
}

@available(iOS 13, *)
protocol CombinePagingInteractorInterface: InteractorInterface {
    func getPokemons(router: Routable) -> AnyPublisher<PokemonsPage, AFError>
}

@available(iOS 13, *)
enum CombinePagingExample {

    struct ViewOutput {
        let restart: AnyPublisher<Void, Never>
        let willDisplayLastCell: AnyPublisher<Void, Never>
    }

    struct ViewInput {
        let pokemon: AnyPublisher<[PokemonTableCellItem], PagingError>
    }
}
