//
//  ConstraintsWireframe.swift
//  Catalog
//
//  Created by Infinum on 30.01.2023..
//  Copyright (c) 2023 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ConstraintsWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController: ConstraintsViewController = .init()
        super.init(viewController: moduleViewController)
        
        let presenter = ConstraintsPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ConstraintsWireframe: ConstraintsWireframeInterface {
}
