//
//  ConstraintsInterfaces.swift
//  Catalog
//
//  Created by Infinum on 30.01.2023..
//  Copyright (c) 2023 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum Constraints {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}

protocol ConstraintsWireframeInterface: WireframeInterface {
}

protocol ConstraintsViewInterface: ViewInterface {
}

protocol ConstraintsPresenterInterface: PresenterInterface {
    func configure(with output: Constraints.ViewOutput) -> Constraints.ViewInput
}
