//
//  RxUIMenuExamplePresenter.swift
//  Catalog
//
//  Created by Sven Svetina on 14.03.2023..
//  Copyright (c) 2023 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class RxUIMenuExamplePresenter {

    // MARK: - Private properties -

    private unowned let view: RxUIMenuExampleViewInterface
    private let wireframe: RxUIMenuExampleWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: RxUIMenuExampleViewInterface,
        wireframe: RxUIMenuExampleWireframeInterface
    ) {
        self.view = view
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension RxUIMenuExamplePresenter: RxUIMenuExamplePresenterInterface {

    func configure(with output: RxUIMenuExample.ViewOutput) -> RxUIMenuExample.ViewInput {
        return RxUIMenuExample.ViewInput()
    }

}
