//
//  CatalogViewController.swift
//  Catalog
//
//  Created by Filip Gulan on 01/02/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CatalogViewController: UITableViewController {

    // MARK: - Public properties -

    var presenter: CatalogPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        _setupUI()
    }
	
}

// MARK: - Extensions -

extension CatalogViewController: CatalogViewInterface {
}

private extension CatalogViewController {
    
    func _setupUI() {
        title = "Catalog"
    }
}
