//
//  CatalogWireframe.swift
//
//  Created by Filip Gulan on 01/02/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CatalogWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = CatalogViewController()
        super.init(viewController: moduleViewController)
        
        let presenter = CatalogPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CatalogWireframe: CatalogWireframeInterface {
    
    func show(_ model: Catalogizable.Type) {
        let viewController = model.viewController
        viewController.title = model.title
        switch model.presentationStyle {
        case .present:
            navigationController?.present(viewController, animated: true, completion: nil)
        case .push:
            navigationController?.pushViewController(viewController, animated: true)
        }
    }
}
