//
//  CatalogPresenter.swift
//  Catalog
//
//  Created by Filip Gulan on 01/02/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CatalogPresenter {

    // MARK: - Private properties -

    private unowned let view: CatalogViewInterface
    private let wireframe: CatalogWireframeInterface

    // MARK: - Lifecycle -

    init(view: CatalogViewInterface, wireframe: CatalogWireframeInterface) {
        self.view = view
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CatalogPresenter: CatalogPresenterInterface {
}
