//
//  CatalogInterfaces.swift
//  Catalog
//
//  Created by Filip Gulan on 01/02/2019.
//  Copyright (c) 2019 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CatalogWireframeInterface: WireframeInterface {
}

protocol CatalogViewInterface: ViewInterface {
}

protocol CatalogPresenterInterface: PresenterInterface {
}
