//
//  KeyboardHandlerViewController.swift
//  Catalog
//
//  Created by Zvonimir Medak on 27.09.2022..
//  Copyright (c) 2022 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine

fileprivate enum Constants {
    static let additionalButtonSpacing: CGFloat = 10
}

@available(iOS 13.0, *)
final class KeyboardHandlerViewController: KeyboardHandlingViewController {

    // MARK: - IBOutlets -

    @IBOutlet private weak var scrollView: UIScrollView!

    // MARK: - Constraints -

    @IBOutlet private weak var buttonBottomConstraint: NSLayoutConstraint!

    // MARK: - Private properties -

    private var keyboardCancellable: AnyCancellable?

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

@available(iOS 13.0, *)
private extension KeyboardHandlerViewController {

    func setupView() {
        setupKeyboardHandling()

        tableDataSource.items = [

        ]
    }

    func setupKeyboardHandling() {

        let animationHandler: (Double) -> Void = { [unowned self] animationDuration in
            UIView.animate(
                withDuration: animationDuration,
                delay: 0,
                usingSpringWithDamping: 0.75,
                initialSpringVelocity: 0.1,
                options: [.allowUserInteraction, .curveEaseInOut],
                animations: {
                    self.view.layoutIfNeeded()
                }
            )
        }

        let keyboardPresentationHandler: (KeyboardHandler.PresentingParams) -> Void = { [unowned self] params in
            handleKeyboardPresentation(
                bottomConstraint: buttonBottomConstraint,
                defaultMargin: Constants.additionalButtonSpacing,
                parameters: params
            )
            animationHandler(params.animationDuration * 2.25)
        }
        keyboardCancellable = KeyboardHandler.register(handler: keyboardPresentationHandler)
    }
}


@available(iOS 13.0, *)
extension KeyboardHandlerViewController: Catalogizable {

    static var title: String {
        return "Keyboard Handling"
    }

    static var viewController: UIViewController {
        return UIStoryboard(name: "KeyboardHandling", bundle: nil)
            .instantiateViewController(ofType: KeyboardHandlingViewController.self)
    }
}
