//
//  LineHeightPresenter.swift
//  Catalog
//
//  Created by Damjan Dimovski on 16.2.22.
//  Copyright (c) 2022 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LineHeightPresenter {

    // MARK: - Private properties -

    private unowned let view: LineHeightViewInterface
    private let wireframe: LineHeightWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: LineHeightViewInterface,
        wireframe: LineHeightWireframeInterface
    ) {
        self.view = view
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension LineHeightPresenter: LineHeightPresenterInterface {
}
