//
//  LineHeightInterfaces.swift
//  Catalog
//
//  Created by Damjan Dimovski on 16.2.22.
//  Copyright (c) 2022 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol LineHeightWireframeInterface: WireframeInterface {
}

protocol LineHeightViewInterface: ViewInterface {
}

protocol LineHeightPresenterInterface: PresenterInterface {
}
