//
//  LineHeightWireframe.swift
//  Catalog
//
//  Created by Damjan Dimovski on 16.2.22.
//  Copyright (c) 2022 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LineHeightWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "LineHeight", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: LineHeightViewController.self)
        super.init(viewController: moduleViewController)

        let presenter = LineHeightPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension LineHeightWireframe: LineHeightWireframeInterface {
}
